### ISSUE TITLE
https protocol

### ISSUE THREAD

**Issue by ViKapitoshka** [x0v/x0v.github.io#1]
how you implement the use of https ? I use cloud flare, but now my website 403 error

**Comment by x0v** [comment]
Hey @ViKapitoshka 
I simply followed these instructions
and it worked fine. Changes may take sometime to reflect, but it shouldn't have shown `403`
Check again.

**Comment by ViKapitoshka** [comment]
@x0v , my site worked fine all the time, but for some reason today decided to issue this error...
you have an ssl certificate from CloudFlare too?

**Comment by x0v** [comment]
Yes

**Comment by ViKapitoshka** [comment]
what instructions were you doing?

**Comment by x0v** [comment]
I have already given you a link in my earlier comment. That is what exactly I followed.

**Comment by ViKapitoshka** [comment]
sorry, the first link is not displayed, thank you very much!

**Comment by x0v** [comment]
@ViKapitoshka your welcome
